/* 
Automatically generated code. Do not edit this file.

To use, ensure the following:

1. That this code is copied into the application that is going to use the server.
2. That server-bridge-superagent-client is added as a dependency in the application. Install it by running:

   npm install --save server-bridge-superagent-client

3. Include the typescript definition file for server-bridge-superagent-client in your application. 
   You can easily add it by running...

   tsd link 

   ...if you are using tsd (http://definitelytyped.org/tsd/)

4. That the import paths in this file are correct. If they aren't, change the code
    generation script to generate the correct paths.
*/

import {ClientBase} from "server-bridge-superagent-client";
import {FoodItem} from "./food-item";
import {Order} from "./order";

export class ServerFoodItems extends ClientBase {
   constructor(options?: { urlPrefix: string; }) {
       super((options == null ? "" : (options.urlPrefix || "")) + "/food-items");
   }

   list() {
       return super.get<FoodItem[]>("/list");
   }

   remove(opts: { foodItemID: string; }) {
       return super.post<number>("/remove", opts);
   }

   set(foodItem: FoodItem) {
       return super.post<FoodItem>("/", foodItem);
   }
}

export class ServerOrders extends ClientBase {
   constructor(options?: { urlPrefix: string; }) {
       super((options == null ? "" : (options.urlPrefix || "")) + "/orders");
   }

   list() {
       return super.get<Order[]>("/list");
   }

   remove(opts: { orderID: string; }) {
       return super.post<number>("/remove", opts);
   }

   set(order: Order) {
       return super.post<Order>("/", order);
   }
}
